import { describe, expect, it } from "vitest";
import analysis from "../fixtures/golden_analysis_single_asin.json" with { type: "json" };
import { renderReport } from "../../scripts/render_report.js";
import { checkHtml } from "../../scripts/agent_contract_check.js";

describe("report renderer", () => {
  it("renders required sections and highlighted theme details", async () => {
    const html = await renderReport(analysis as any);
    expect(html).toContain("id=\"scope\"");
    expect(html).toContain("id=\"voc-theme-map\"");
    expect(html).toContain('href="#scope">1. 数据范围与口径</a>');
    expect(html).toContain('href="#health">2. Review 健康度</a>');
    expect(html).toContain('class="toc-group" open');
    expect(html).toContain(".toc-group:not([open]) > .toc-sublist");
    expect(html).toContain('href="#key-insights">3. 关键结论</a>');
    expect(html).toContain("toc-sublist toc-key-insights");
    expect(html).toContain('href="#key-insight-audience">3.1 人群</a>');
    expect(html).toContain('href="#key-insight-dissatisfaction">3.8 不满意点</a>');
    expect(html).toContain('href="#voc-theme-map">4. VOC 主题地图</a>');
    expect(html).toContain("toc-sublist toc-voc-themes");
    expect(html).toContain('href="#voc-theme-theme_family_party">4.1');
    expect(html).toContain('href="#actions">5. 机会矩阵与业务动作</a>');
    expect(html).toContain('href="#limits">6. 限制与 Checkpoint</a>');
    expect(html).not.toContain('<h3 class="section-subtitle">八类横向洞察</h3>');
    expect(html).not.toContain('<h3 class="section-subtitle">主题与观点分布</h3>');
    expect(html).not.toContain("section-kicker");
    expect(html).not.toContain("按业务方向拆分");
    expect(html).toContain("section-title-with-help");
    expect(html).toContain("help-badge");
    expect(html).toContain("❓");
    expect(html).toContain("关键结论回答八个横向问题");
    expect(html).toContain("VOC 主题地图回答哪些跨评论问题或机会需要被业务处理");
    expect(html).toContain("运营优先级表示动作顺序");
    expect(html).toContain("P0 是立即处理");
    expect(html).toContain("提及：");
    expect(html).toContain("置信度：");
    expect(html).toContain("主题类型：");
    expect(html).toContain("严重度：");
    expect(html).toContain("运营优先级：");
    expect(html).toContain("P1 本轮放大机会");
    expect(html).toContain("P1 本轮闭环风险");
    expect(html).toContain("运营动作：");
    expect(html).toContain("运营要把它当作转化主线放大");
    expect(html).toContain("运营要在本轮建立止损闭环");
    expect(html).not.toContain('<span class="badge">优先级：P1</span>');
    expect(html).not.toContain("@media (max-width");
    expect(html).toContain("report-block insight-block");
    expect(html).toContain('id="key-insight-audience"');
    expect(html).toContain("report-block theme-card theme-card-clickable");
    expect(html).toContain('id="voc-theme-theme_family_party"');
    expect(html).toContain("report-block action-group");
    expect(html).toContain("action-card-list");
    expect(html).toContain("theme-detail-theme_family_party");
    expect(html).toContain("viewpoint-distribution");
    expect(html).not.toContain("<th>角色</th>");
    expect(html).not.toContain("data-viewpoint-role");
    expect(html).not.toContain("insight-grid");
    expect(html).toContain('data-open-mode="new-tab"');
    expect(html).toContain("theme-card-clickable");
    expect(html).toContain('data-card-target="#theme-detail-theme_family_party"');
    expect(html).toContain('href="#theme-detail-theme_family_party" target="_blank" rel="noopener"');
    expect(html).toContain("sticky-theme-card");
    expect(html).toContain('class="card sticky-theme-card theme-filter-panel"');
    expect(html).toContain("theme-detail-context");
    expect(html).toContain("theme-filter-area");
    expect(html).toContain("核心问题：");
    expect(html).toContain("归因假设：");
    expect(html).toContain("业务含义：");
    expect(html).toContain("运营动作：");
    expect(html).not.toContain('class="theme-context-line subtle"');
    expect(html).toContain("theme-detail-mode");
    expect(html).toContain("theme-detail-active");
    expect(html).toContain(".theme-detail { display: none;");
    expect(html).toContain(".theme-detail-mode .main > section { display: none;");
    expect(html).toContain("theme-filter-controls");
    expect(html).toContain('data-theme-filter="all"');
    expect(html).toContain('data-theme-filter="vp_family_children_party"');
    expect(html).toContain("data-theme-review");
    expect(html).toContain("data-viewpoints=");
    expect(html).not.toContain("voc-viewpoint-detail-");
    expect(html).not.toContain('class="section-title">主题详情：');
    expect(html).toContain("<mark>");
    const result = checkHtml(html);
    expect(result.errors).toEqual([]);
  });
});
